import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
// import "bootstrap/dist/css/bootstrap.min.css";
// import Carousel from "react-bootstrap/Carousel";
import {
  AiOutlineLinkedin,
  AiOutlineDribbble,
  AiFillPhone,
  AiFillFacebook,
} from "react-icons/ai";
// import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
// import {faLinkedinIn,faGithub,faDribbble} from "@fortawesome/free-brands-svg-icons"
// import {faHandPointer,faPaperPlane} from "@fortawesome/free-regular-svg-icons"
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen ">
          <nav className="py-5  mb-0 flex justify-between">
            <h1 className="text-xl font-mono ">developedbyawnish</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="#"
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white text-center px-4 py-2 rounded-md ml-8 text-decoration-none"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              Awnish Mehta
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Frontend Developer & Designer.
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto ">
              Providing Service for Web Designe and content need. Join me below
              and let's get cracking!
            </p>
          </div>

          <div className="text-4xl flex justify-center gap-16  cursor-pointer">
            <a href="#" className="text-gray-600">
              <AiOutlineDribbble />
            </a>
            <a href="#" className="text-gray-600">
              <AiOutlineLinkedin />
            </a>
            <a href="#" className="text-gray-600">
              <AiFillFacebook />
            </a>
            {/* <a href="#" className="text-gray-600"><AiFillPhone/></a>   */}
            {/* <FontAwesomeIcon icon={faDribbble}></FontAwesomeIcon> */}
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1 my-5">Services I Offer </h3>
            <p className="text-md py-2 text-gray-800 md:text-xl  mx-auto ">
              Since the beginning of ,y journey as a Frontend Developer &
              Designer , I've done work for
              <span className="text-teal-500"> company </span>
              consulted for <span className="text-teal-500"> startups </span>
              and collaborated with talanted peoples to create digital products
              for both business and consumer use.
            </p>
          </div>

          <div className="text-center justify-center 2xl:flex xl:flex lg:flex md:block gap-10 mx-auto">
            <div className="text-center shadow-lg p-5 rounded-xl my-5 cursor-pointer">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-2 pb-2">
                {" "}
                Beautiful Designs
              </h3>
              <p>Creating elegant design suited for your needs</p>
              <h4 className="py-2 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 ">Photoshop</p>
              <p className="text-gray-800 ">Illustrator</p>
              <p className="text-gray-800 ">Adobe Dimension</p>
              <p className="text-gray-800 ">Figma</p>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-5 cursor-pointer">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-2 pb-2">
                {" "}
                Beautiful Designs
              </h3>
              <p>Creating elegant design suited for your needs</p>
              <h4 className="py-2 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 ">Photoshop</p>
              <p className="text-gray-800 ">Illustrator</p>
              <p className="text-gray-800 ">Adobe Dimension</p>
              <p className="text-gray-800 ">Figma</p>
            </div>
            <div className="text-center shadow-lg p-5 rounded-xl my-5 cursor-pointer">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-2 pb-2">
                {" "}
                Beautiful Designs
              </h3>
              <p>Creating elegant design suited for your needs</p>
              <h4 className="py-2 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 ">Photoshop</p>
              <p className="text-gray-800 ">Illustrator</p>
              <p className="text-gray-800 ">Adobe Dimension</p>
              <p className="text-gray-800 ">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div className="text-center">
            <h3 className="text-3xl py-1 my-3">Portfolio</h3>
            <p className="text-md py-1 leading-8 text-gray-80">
              Since the beginning of ,y journey as a Frontend Developer &
              Designer , I've done work for
              <span className="text-teal-500"> company </span>
              consulted for <span className="text-teal-500"> startups </span>
              and collaborated with talanted peoples to create digital products
              for both business and consumer use.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

{
  /* <Carousel>
<Carousel.Item>
  <img
    className="d-block w-100 "
    src="https://soliloquywp.com/wp-content/uploads/2013/05/action-backlit-beach-1046896-1200x450_c.jpg"
    alt="First slide"
  />
  <Carousel.Caption>
    <h3>First slide label</h3>
    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
  </Carousel.Caption>
</Carousel.Item>
<Carousel.Item>
  <img
    className="d-block w-100 "
    src="https://soliloquywp.com/wp-content/uploads/2013/05/artistic-backlit-creative-532285-1200x450_c.jpg"
    alt="Second slide"
  />

  <Carousel.Caption>
    <h3>Second slide label</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
  </Carousel.Caption>
</Carousel.Item>
<Carousel.Item>
  <img
    className="d-block w-100 "
    src="https://soliloquywp.com/wp-content/uploads/2013/05/backlit-beach-clouds-1005198-1200x450_c.jpg"
    alt="Third slide"
  />

  <Carousel.Caption>
    <h3>Third slide label</h3>
    <p>
      Praesent commodo cursus magna, vel scelerisque nisl consectetur.
    </p>
  </Carousel.Caption>
</Carousel.Item>
</Carousel> */
}
